// Code generated by go generate. DO NOT EDIT.

//go:generate rm pkg.go
//go:generate go run ../gen/gen.go

package dagger

import (
	"cuelang.org/go/internal/core/adt"
	"cuelang.org/go/pkg/internal"
)

func init() {
	internal.Register("dagger", pkg)
}

var _ = adt.TopKind // in case the adt package isn't used

var pkg = &internal.Package{
	Native: []*internal.Builtin{{
		Name: "Shell",
		Params: []internal.Param{
			{Kind: adt.StructKind},
		},
		Result: adt.TopKind,
		Func: func(c *internal.CallCtxt) {
			config := c.Struct(0)
			if c.Do() {
				c.Ret, c.Err = Shell(config)
			}
		},
	}},
}
